title: d3-s0
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  d3-s0

# Build settings
theme: minima
plugins:
  - jekyll-feed

